#!/usr/bin/env python3

"""
Author            : Nohavye
Author's Email    : noha.poncelet@gmail.com
Repository        : https://github.com/vixen-shell/vixen-environment.git
Description       : vxm executable.
License           : GPL3
"""

import argparse, importlib.util
from vixen_lib import packages

def get_setup_module(path: str):
    spec = importlib.util.spec_from_file_location('setup', f'{path}/vxm.setup.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description = f"""
        Vixen Manager.
    """)

    parser.add_argument('--install', '-i', type = str, help = 'Install vixen feature. (Vixen feature path)')
    parser.add_argument('--update', '-u', type = str, help = 'Update vixen feature. (Vixen feature path)')
    parser.add_argument('--remove', '-r', type = str, help = 'Remove vixen feature. (Vixen feature path)')

    args = parser.parse_args()

    if args.install: packages.Setup(get_setup_module(args.install).setup).process()
    if args.update: packages.Setup(get_setup_module(args.update).update).process()
    if args.remove: packages.Setup(get_setup_module(args.remove).remove).process()